services:
  - type: web
    name: linkedin-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: RENDER
        value: "true"
    packages:
      - chromium-browser
      - chromium-chromedriver
    healthCheckPath: /status
    autoDeploy: false
    disk:
      name: chrome-data
      mountPath: /tmp
      sizeGB: 1