services:
  - type: web
    name: linkedin-scraper
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: RENDER
        value: "true"
      - key: PORT
        value: "10000"
      - key: SHEET_ID
        value: 1srvBC83XVx1LS4d8gIiwkWM41sS0Yu3puOHmzwlixrY
      - key: APIFY_TOKEN
        sync: false # This makes it a secret
      - key: LINKEDIN_USERNAME
        sync: false # This makes it a secret
      - key: LINKEDIN_PASSWORD
        sync: false # This makes it a secret
    healthCheckPath: /status
    autoDeploy: false